#!/bin/bash

log_fail() {
  printf "\033[0;37m[\033[1;35m$(date +%H:%M:%S)\033[0;37m] \033[1;31m%s\033[0m\n" "$1" 1>&2
}

e_header() {
  printf " \033[37;1m%s\033[m\n" "$*"
}

e_done() {
  printf " \033[37;1m%s\033[m...\033[32mOK\033[m\n" "✔ $*"
}

if [ -z "${DOTFILES_ROOT:-}" ]; then
  DOTFILES_ROOT="$HOME/src/github.com/mishiwata1015/dotfiles"; export DOTFILES_ROOT
fi
DOTFILES_GITHUB="git@github.com:mishiwata1015/dotfiles.git"; export DOTFILES_GITHUB

# 1. Download dotfiles repository to $DOTFILES_ROOT.
if [ -d "$DOTFILES_ROOT" ]; then
  log_fail "$DOTFILES_ROOT: already exists"
  exit 1
fi

printf "\n" && e_header "Downloading dotfiles..."
mkdir -p "$(dirname "$DOTFILES_ROOT")"
git clone "$DOTFILES_GITHUB" "$DOTFILES_ROOT"
printf "\n" && e_done "Download"

# 2. Deploy dotfiles to home directory.
printf "\n" && e_header "Deploying dotfiles..."
cd "$DOTFILES_ROOT"
make deploy &&
printf "\n" && e_done "Deploy" &&

# 3. Initialize dotfiles.
printf "\n" &&
e_header "Initializing dotfiles..." &&
make init &&
printf "\n" && e_done "Initialize"
