tap "homebrew/core"

brew 'git'
brew 'nodenv'
brew 'rbenv'
brew "awscli"
brew "jq"
brew "tig"
brew "tmux"
brew "tree"
brew "yarn"
brew "zsh-completions"
brew "zsh"

# cask 'deepl' # Download from https://www.deepl.com/translator
# cask 'zoom' # Download from https://zoom.us/download
cask '1password'
cask 'alfred'
cask 'bitwarden'
cask 'clipy'
cask 'dash'
cask 'docker'
cask 'evernote'
cask 'figma'
cask 'google-chrome'
cask 'graphiql'
cask 'gyazo'
cask 'hammerspoon'
cask 'insomnia'
cask 'iterm2'
cask 'karabiner-elements'
cask 'kindle'
cask 'sequel-pro'
cask 'skitch'
cask 'slack'
cask 'spectacle'
cask 'virtualbox'
cask 'visual-studio-code'
